[package]
publish = false
name = "lexopt-c"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
lexopt = "=0.3.0"

[build-dependencies]
cbindgen = "0.27.0"

[dev-dependencies]
cc = "1.1.24"
